FROM public.ecr.aws/lambda/python:3.10

WORKDIR ${LAMBDA_TASK_ROOT}

COPY ./requirements.txt ./

RUN pip install --no-cache-dir --upgrade -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
RUN pip install "fastapi[standard]" --target "${LAMBDA_TASK_ROOT}"

COPY ./app/app.py ${LAMBDA_TASK_ROOT}

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["app.handler"]